### ISSUE TITLE
Regrading Readme.md file

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Satakshijain/CodingHustlers#26]
Add a proper readme.md file so every one will know more about the project and the tech stacks used.#gssoc24

**Comment by yashisrani** [comment]
@Satakshijain kindly assign me this issue under gssoc'24. i will create better & good looking Readme file for this project.

**Comment by SuhainaFathimaM** [comment]
@Satakshijain kindly assign me this issue under gssoc'24. I will create better & good looking Readme file for this project.
