### ISSUE TITLE
The Uneven Navbar

### ISSUE THREAD

**Issue by ayush-848** [Satakshijain/CodingHustlers#38]
![image](https://github.com/Satakshijain/CodingHustlers/assets/126975547/90236b50-b3cb-4256-9d1e-d392c4675f85)

The navbar items should be in a single line and the navbar style and color should be more enhanced.

**Comment by krish-san** [comment]
Hello, I'm interested in contributing to this issue in GSSoc'24. I propose adding a toggle button to the navigation bar to ensure it's displayed evenly and attractively. Additionally, I can arrange the important elements in a more visually appealing manner. I'm also open to incorporating any other features you'd like to see in the navigation bar. Please assign me to this issue.

**Comment by ayushrskiaa** [comment]
I'm interested in contributing to it under GSSOC'24. I can fix it in a better way and additionally I can add dark mode feature with toggle button. Kindly assign it to me.
Thank you.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me.
