### ISSUE TITLE
Aligning this the programming language icons 

### ISSUE THREAD

**Issue by Sibam-Paul** [Satakshijain/CodingHustlers#73]
### Hey working on the programming language icons

**Image reference**
![image](https://github.com/Satakshijain/CodingHustlers/assets/158052549/c35a2df5-6a18-47da-8343-a08d7da66b5e)

**Fixing :-**
Will align it nicely

**I am working on this project please assign it to me and mention GSSOC'24 badge **

**Comment by SamarWats** [comment]
Hii @Satakshijain  I can allign the images as per the requirement. Please assign me this issue.
